### ISSUE TITLE
Rename nvm virtual to nvm4win if can't resolve conflict with nvm owner

### ISSUE THREAD

**Issue by espoelstra** [arieljannai/chocolatey-nvm-windows#2]
I've contacted the maintainer of https://chocolatey.org/packages/nvm about renaming his to nvm.install since he's trying to run the installer (and apparently not successfully in the first attempt). If he doesn't want to change it we can move to nvm4win or something similar and just use nvm in the package tags to get it to show up higher in searches.

**Comment by arieljannai** [comment]
One of the things that were told to me in the first report when I uploaded the package, was to rename mine from nvm.portable to nvm and use also a virtual package.
I don't see a reason that he won't agree, since we are trying to accomplish the same thing - nvm in choco.
If he doesn't repsond, maybe chocolatey reviewers/maintainers can help us get the correct package name

**Comment by espoelstra** [comment]
I also asked the Chocolatey admins about this since the other nvm package never made it out of the verification stage. We'll see if they get back to me soon about taking over the nvm name since the other one seems abandoned since around 5 months ago and was using the installer so could exist as nvm.install instead of taking up nvm.

**Comment by espoelstra** [comment]
I was added as a co-maintainer on `nvm`, and nvm.portable was accepted to the feed, so I'll see about pushing the nvm virtual/meta package soon.

**Comment by espoelstra** [comment]
The virtual was created and takes over the nvm namespace and pulls in nvm.portable per the (at the time) Chocolatey recommended naming scheme.
